name: build

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: >
      github.event.issue.pull_request != null && contains(github.event.comment.body, '/build')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      # Build the mod
      - run: ./gradlew build